CREATE TABLE
IF NOT EXISTS users
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	points INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE
IF NOT EXISTS events
(
	[id] INTEGER PRIMARY KEY AUTOINCREMENT,
	[name] TEXT NOT NULL,
	[description] TEXT NOT NULL,
	[start_time] TEXT NOT NULL,
	[end_time] TEXT NOT NULL,
	[date] DATE NOT NULL,
	[user_id] INTEGER NOT NULL REFERENCES users
(id)
);
